# Site settings
name: Beach Site
email: zangshayang1@hotmail.com
author: Shayang Zang
url: 
resume_site: 
github: https://github.com/zangshayang1/
baseurl: ""
description: No time for description.
meta_description: 臧沙洋的静态技术博客。
motto: Work. Think. Speak.
banner: 业精于勤荒于嬉 行成于思毁于随

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: zangshayang1
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : disqus
    disqus :
        short_name : zangshayang1-github-io
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
